name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Run Electric Trains build script
        run: |
          chmod +x build.sh
          sudo apt-get install -y libxml2-utils
          ./build.sh

      - name: Upload Built ZIP file
        uses: actions/upload-artifact@v3
        with:
          name: electric-trains-latest
          path: electric-trains_0.2.14.zip  # Replace with the path to your zip file
